# Generated by Django 3.0.5 on 2020-06-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='tempratute',
            new_name='temprature',
        ),
    ]
